name: eth_returns_forecaster_env
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python
  - ipykernel
  - jupyterlab
  - pandas
  - scikit-learn
  - matplotlib
  - numpy
  - statsmodels
  - pmdarima
  - arch-py
  - pip
  - pip:
    - influxdb-client
